export enum Icon {
  Globe = 'globe',
  Mountain = 'mountain',
  Gear = 'gear',
  User = 'user',
  Glip = 'flip',
  GearUser = 'gear-user',
  Heart = 'heart',
  Jobs = 'jobs',
  Phone = 'phone',
  Mail = 'mail',
  Fb = 'fb',
  In = 'in',
  Insta = 'insta',
  Facebook = 'facebook',
  LinkedIn = 'linked-in',
  Instagram = 'instagram',
  ArrowLeft = 'arrow-left',
  ArrowRight = 'arrow-right',
  ArrowDown = 'arrow-down',
  ArrowUp = 'arrow-up',
}